### ISSUE TITLE
Error appending a second int -- not sure what the problem is here

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/common-python#4]
So since SearchCriteria is a list, I assumed it will accept any type of elements. However, I can't append a second int to it. The first one was successfully appended, but the second one crashes:

sc = SearchCriteria()
sc.append(1)
## In [12]: sc.append(2)

AttributeError                            Traceback (most recent call last)
<ipython-input-12-58c28c98edaf> in <module>()
----> 1 sc.append(2)

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/hgicommon/collections.py in append(self, search_criterion)
     20     def append(self, search_criterion: SearchCriterion):
     21         for existing_search_criterion in self:
---> 22             if existing_search_criterion.attribute == search_criterion.attribute:
     23                 raise ValueError(SearchCriteria._DUPLICATE_ERROR_MESSAGE)
     24         super(SearchCriteria, self).append(search_criterion)

AttributeError: 'int' object has no attribute 'attribute'

**Comment by irinaColgiu** [comment]
Same error when trying to extend:
sc1 = SearchCriteria()
**In [20]: sc1.extend({1:'a'})**
<ipython-input-20-acd9f263518e> in <module>()
----> 1 sc1.extend({1:'a'})

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/hgicommon/collections.py in extend(self, iterable)
     26     def extend(self, iterable):
     27         for search_criteria in iterable:
---> 28             self.append(search_criteria)
     29 
     30     def **setitem**(self, key, value):

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/hgicommon/collections.py in append(self, search_criterion)
     20     def append(self, search_criterion: SearchCriterion):
     21         for existing_search_criterion in self:
---> 22             if existing_search_criterion.attribute == search_criterion.attribute:
     23                 raise ValueError(SearchCriteria._DUPLICATE_ERROR_MESSAGE)
     24         super(SearchCriteria, self).append(search_criterion)

AttributeError: 'int' object has no attribute 'attribute'

**Comment by colin-nolan** [comment]
The issue is `SearchCriteria` is a collection of `SearchCriterion` instances. It doesn't make sense to append an `int` into the collection. The same applies for extending the collection with a `dict`.

**Comment by irinaColgiu** [comment]
I think if there is an append method there, I should get back a ValueError if they type I am trying to append is wrong, but not the exception above.
