### ISSUE TITLE
Add to SearchCriteria class a method for removing and replacing a criterion by attribute name 

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/common-python#5]
A suggestion would be to add a method also for **removing a criterion** based on the attribute name. At the moment the only possibility to remove a criterion from a SearchCriteria object is pop(idx), but for that to use you need to know the index of an element, which is not easy to find (one would have to iterate over all the criteria and check on the attribute).
Also replace would be helpful.

Cheers,
Irina

**Comment by colin-nolan** [comment]
Fixed in https://github.com/wtsi-hgi/python-common/commit/f1a7d6560406e3c79777c4d17e68acea0f947f1e.

Added ability to delete by attribute using:
`delete_serach_criteria_for_attribute`

Also added ability to use `del` command:
`del search_criteria[2]`
