### ISSUE TITLE
Remove unnecesary method Metadata.values()

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/common-python#6]
Currently the values()  method from Metadata class is fetching all the values and only the values stored in the Metadata object:

```
   def values(self) -> Iterable(Any):
        return self._data.values()

```

https://github.com/wtsi-hgi/python-common/blob/master/hgicommon/collections.py#L70

I am pretty sure that there will never be the case when one wants to fetch only the values for the metadata for a file. And the reason for that is that a value of say "1" has no meaning unless it has also the attribute name attached to it. So you can't give the values a meaning unless you have also the attribute names attached.

p.s. I could just do this, but then I don't know how many client libraries depend on python-common and what impact any change has to the client code.

**Comment by colin-nolan** [comment]
I agree. `Metadata` was originally implemented as a dict-like collection and, as such, has a `values` method. I doubt there is any reason for the method to exist other than to satisfy the interface.

**Comment by colin-nolan** [comment]
Although we don't anticipate much use of this method through our currently use of `Metadata`, it is required by the interface (https://docs.python.org/3/library/collections.abc.html) and therefore I shall leave it be.
