### ISSUE TITLE
Change Metadata class to use 1 Lock because it is not thread safe with a non-safe dict of Locks

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/common-python#8]
Imported issue opened by Irina in https://github.com/wtsi-hgi/python-baton-wrapper/issues/26:

> I just realized that Metadata class is not thread-safe exactly because of the dict of Locks which is not thread-safe. You are making a dict-like structure thread-safe, with a non-safe dict...
> What happens if 2 threads want to insert in the Metadata the same key (different values) for the first time? So thread1 reads the dict of Locks, sees that there is no Lock for KeyX and starts the procedure of creating a Lock. Meanwhile thread2 reads the dict of Locks, sees that there is no Lock for KeyX and starts the procedure of creating a Lock...They both obtain a Lock so they are both good to write to the Metadata._data...
> And you are back to solving problem number 1..

**Comment by colin-nolan** [comment]
Good spot - I foolishly assumed defaultdict would be threadsafe.

**Comment by colin-nolan** [comment]
Related comments from Irina, imported from https://github.com/wtsi-hgi/python-baton-wrapper/issues/25:

> Speaking of thread-safety in Metadata class, I have the following questions/issues:
> - do we really need a dict of Locks for the Metadata? Isn't it more clear, simple and elegant to have just 1 Lock for this class? A thread could acquire and block the whole Metadata object while modifying, instead of 1 thread acquiring X Locks and spending some time before the guarded block of code acquiring X locks, and then spending another amount of time releasing X Locks? It will use at least double the amount of memory because you keep 2 dicts instead of 1 with the same length. Though we are not short on memory in this case, I don't think this dict of Locks makes any improvement in terms of runtime, on the contrary, plus it adds quite a bit of complexity to the code
> - when using CPython and multithreading you can't run multiple threads simultaneously anyway...
> - is there any use-case in which multiple threads access the same global instance of metadata?

**Comment by colin-nolan** [comment]
Proof that `defaultdict` is not threadsafe:

``` python
_values = []

def object_factory() -> object:
    global _values
    sleep(5)
    created = object()
    _values.append(created)
    return created

my_dict = defaultdict(object_factory)
values_of_foo = []
wait_semaphore = Semaphore(0)

def get_and_store_foo_value():
    values_of_foo.append(my_dict["foo"])
    wait_semaphore.release()

Thread(target=get_and_store_foo_value).start()
get_and_store_foo_value()

wait_semaphore.acquire()
wait_semaphore.acquire()
assert values_of_foo[0] == values_of_foo[1]    # This will fail!
```

**Comment by Xophmeister** [comment]
For information's sake: Various sources suggest that `defaultdict` (and `dict`) will not be thread-safe (in CPython) whenever any of the following are implemented with Python code:
- Key hashing and/or comparison (i.e., the key is an object with custom `__hash__`, `__eq__` or `__cmp__` methods);
- Value construction (i.e., using a custom factory function/object constructor)

Key-value pairing is done with a single bytecode operation, so internal types (e.g., `DefaultDict[str, List[Any]]`, etc.) _should_ be safe as they'd be entirely delegated to the C runtime. However, as soon as Python code is involved, it will get compiled into additional bytecode instructions that could be unsafely interleaved in a threading situation.

Interestingly, that implies that `DefaultDict[str, Lock]` _would_ be thread-safe in CPython, as [`threading.Lock` is implemented in C](https://github.com/python/cpython/blob/3.5/Modules/_threadmodule.c)... However, I'm not willing to risk it :wink: and your `ThreadSafeDefaultdict` makes things clear, without having to trawl through the CPython source!
